### ISSUE TITLE
[feature request] Add description to all methods so they appear in intellisense.

### ISSUE THREAD

**Issue by trusktr** [TypeCtrl/tinycolor#182]
The README has some nice documentation, but none of this appears inside VS Code when using intellisense. For example, hovering on the `mix` method I see the following tooltip:

![tooltip-with-no-description](https://user-images.githubusercontent.com/297678/80261730-16fe1280-8640-11ea-933f-64db80f83a2f.png)

The tooltip has no helpful description.

As an example, we can write a description on a method in JSDoc format like this:

![Screenshot from 2020-04-24 15-29-06](https://user-images.githubusercontent.com/297678/80261878-95f34b00-8640-11ea-9555-250bfaef5321.png)

Then when we hover on it in other place we see the JSDoc description in the tooltip:

![helpful-info](https://user-images.githubusercontent.com/297678/80261917-b58a7380-8640-11ea-9b91-2653ab900789.png)

**Comment by scttcper** [comment]
I think the latest version should have the jsdocs
