### ISSUE TITLE
s=0 sets h=0, v=0 sets both h=0,s=0

### ISSUE THREAD

**Issue by insad** [TypeCtrl/tinycolor#190]
Creating a new TinyColor object from HSV, with s=0, internally somehow also h is set to 0:

```
c = new TinyColor({ h: 200, s: 0, v: 0.7 }).toHsv();
console.log(c.h, c.s, c.v);
Result: 0, 0, 0.7
Expected result: 200, 0, 0.7
```

and setting v=0, both h and s are set internally to 0:

```
c = new TinyColor({ h: 200, s: 0.5, v: 0 }).toHsv();
console.log(c.h, c.s, c.v);
Result: 0, 0, 0
Expected result: 200, 0.5, 0
```

**Comment by scttcper** [comment]
Tinycolor stores all inputs as an RGB so your hsv is converted to rgb then back to hsv. The values will not be the same, but it will output the same color.

```ts
new TinyColor({ h: 200, s: 0.5, v: 0 }).toHex() === new TinyColor({ h: 0, s: 0, v: 0 }).toHex()
```
