### ISSUE TITLE
Not compatible with IE11

### ISSUE THREAD

**Issue by jeandat** [TypeCtrl/tinycolor#191]
It it me or compatibility with es5 only browser has been dropped in 3.x branch?
Compiled code contains ES6 syntax which then crash in IE11 with `SCRIPT1003: Expected ':'`.

**Comment by scttcper** [comment]
How are you using tinycolor? Are you using the `tinycolor.umd.min.js`?

**Comment by jeandat** [comment]
I'm using the modern `import` syntax:
```
import { isReadable, TinyColor } from '@ctrl/tinycolor';
```

The build is managed by the angular CLI. 

I have no problem with tinycolor 2.x releases.

**Comment by scttcper** [comment]
angular-cli i think should be using the "module" field which would allow us to keep the es2018 build for node and an es5 build for browsers

**Comment by jeandat** [comment]
Indeed angular pick the module folder. Thanks.
Jean
