### ISSUE TITLE
Credit the original author

### ISSUE THREAD

**Issue by yairEO** [TypeCtrl/tinycolor#86]
I did not find any credit to the original author of this "cloned" repo:

https://github.com/bgrins/TinyColor

I would like to use your code since it seems better maintained, **but** I fell that moral demands a credit should be givven since I've been used the real "tinyColor" years ago from the original repo

**Comment by scttcper** [comment]
It’s like the first line of the readme and was working with bgrins on forking the code back into his repo. It’s on a branch called v2 but hasn’t moved much

**Comment by yairEO** [comment]
ho I've missed that top line in the readme. good work mate!
