### ISSUE TITLE
getAlpha() class method is missing

### ISSUE THREAD

**Issue by c0bra** [TypeCtrl/tinycolor#89]
^ title says it all

**Comment by mikaello** [comment]
It seems as you can just refer to alpha as `a` directly from the `TinyColor`-object, from the tests:

```typescript
const hexSetter = new TinyColor('rgba(255, 0, 0, 1)');

// Alpha should start as 1
expect(hexSetter.a).toBe(1);

hexSetter.setAlpha(0.5);
// setAlpha should change alpha value
expect(hexSetter.a).toBe(0.5);
```

Anyways, for backwards compatibility I guess it would be nice to have `getAlpha()`, so either it [should be added](https://github.com/TypeCtrl/tinycolor/pull/106), or `getAlpha()` should be removed from [the documentation](https://github.com/TypeCtrl/tinycolor#getalpha).
